version: 2
jobs:
          build:  # required for runs that don't use workflows
              working_directory: ~/circleci-demo-python-django
              docker:
                - image: circleci/python:3.6.4  # primary container for the build jo
              steps: 
                - checkout  # checkout source code to working directory
                - run:
                        command: |  # use pipenv to install dependencies
                                #sudo pip install pipenv
                                #ahinav added this
                                python3 compile.py
                - store_artifacts:
                        path: ~/circleci-demo-python-django/__pycache
                        destination: tr1
